/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resespmasakan;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ResepMasak extends javax.swing.JFrame {
int resep = 0;
    /**
     * Creates new form ResepMasak
     */
    public ResepMasak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuResep = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        judulResep = new javax.swing.JTextField();
        pembuatResep = new javax.swing.JTextField();
        bahanResep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BUKU RESEP MASAKAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setText("Daftar Menu Resep");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        menuResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Judul", "Pembuat", "Bahan-bahan"
            }
        ));
        menuResep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuResepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menuResep);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 560, 140));

        jLabel3.setText("Ingin Tambah Resep ?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel4.setText("Judul");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setText("Pembuat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel6.setText("Bahan-Bahan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        getContentPane().add(judulResep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 230, -1));
        getContentPane().add(pembuatResep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 230, -1));
        getContentPane().add(bahanResep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 350, 80));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 70, -1));

        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, 20));

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      menuResep.setValueAt(judulResep.getText(), resep , 0);
      menuResep.setValueAt(pembuatResep.getText(), resep , 1);
      menuResep.setValueAt(bahanResep.getText(), resep, 2);
      resep=resep+1;
      //digunakan dalam menambahkan resep yang telah di masukan
      
      judulResep.setText("");
      pembuatResep.setText("");
      bahanResep.setText("");//mengosongkan inputan 
            
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel resep = (DefaultTableModel) menuResep.getModel();
         if (menuResep.getSelectedRowCount()== 1){
              resep.removeRow(menuResep.getSelectedRow());
              JOptionPane.showMessageDialog(this,"Resep Berhasil di Hapus");
              //ketika akan hapus resep tidak ada yang dipilih akan keluar pesan yang pertama tetapi jika ada maka akan melakukan penghapusan
         }else{
             JOptionPane.showMessageDialog(this,"Tidak ada resep yang dipilih");
         } 
         
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menuResepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuResepMouseClicked
       DefaultTableModel resep = (DefaultTableModel) menuResep.getModel();
       //alasan menggunakan default tabel karena tidak menggunakan database 
        judulResep.setText(resep.getValueAt(menuResep.getSelectedRow(),0).toString());
        pembuatResep.setText(resep.getValueAt(menuResep.getSelectedRow(),1).toString());
        bahanResep.setText(resep.getValueAt(menuResep.getSelectedRow(),2).toString());
        //untuk melakukan ubah resep jika user ingin melakukan perubahan dengan klik row tabel
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuResepMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       DefaultTableModel resep = (DefaultTableModel) menuResep.getModel();
       //alasan menggunakan default tabel karena tidak menggunakan database 
       
       if(menuResep.getSelectedRowCount()== 1){
           resep.setValueAt(judulResep.getText(), menuResep.getSelectedRow(),0);
          resep.setValueAt(pembuatResep.getText(), menuResep.getSelectedRow(),1); 
          resep.setValueAt(bahanResep.getText(), menuResep.getSelectedRow(),2);
           
            //ketika keadaan benar maka akan melakukan perubahan yang dilakukan
       }else{
          JOptionPane.showMessageDialog(this,"Pilih Resep yang ingin di ubah","Perhatian",JOptionPane.OK_OPTION);//jika rows nya tidak diklik maka akan muncul pesan ini
           
         
         
       }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepMasak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepMasak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepMasak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepMasak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepMasak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bahanResep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulResep;
    private javax.swing.JTable menuResep;
    private javax.swing.JTextField pembuatResep;
    // End of variables declaration//GEN-END:variables
}
